/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia3progra;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author yese
 */
public class telefonos extends javax.swing.JFrame {

    /**
     * Creates new form telefonos
     */
    public telefonos() {
        initComponents();
        btnejecutar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    metodos objeto = new metodos();
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propiedades = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpantalla = new javax.swing.JTextField();
        txtram = new javax.swing.JTextField();
        txtgarantia = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        cmbmarca = new javax.swing.JComboBox<>();
        txtprincipal = new javax.swing.JTextField();
        txtsecundaria = new javax.swing.JTextField();
        btnejecutar = new javax.swing.JButton();
        txtgpu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtbateria = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtcpu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chkflash = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PUNTAJE DE MOVILES");

        jLabel3.setText("Tamano de pantalla:");

        jLabel4.setText("Cantidad de RAM:");

        jLabel5.setText("Tiempo de garantia:");

        jLabel6.setText("Precio:");

        jLabel7.setText("Marca ");

        jLabel8.setText("Camara:");

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });
        txtpantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpantallaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpantallaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantallaKeyTyped(evt);
            }
        });

        txtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtramActionPerformed(evt);
            }
        });
        txtram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtramKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtramKeyTyped(evt);
            }
        });

        txtgarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgarantiaActionPerformed(evt);
            }
        });
        txtgarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgarantiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgarantiaKeyTyped(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprecioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXI", "LENOVO", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "Google", " " }));

        txtprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprincipalActionPerformed(evt);
            }
        });
        txtprincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprincipalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprincipalKeyTyped(evt);
            }
        });

        txtsecundaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsecundariaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsecundariaKeyTyped(evt);
            }
        });

        btnejecutar.setText("Ejecutar");
        btnejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnejecutarActionPerformed(evt);
            }
        });

        txtgpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgpuKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgpuKeyTyped(evt);
            }
        });

        jLabel9.setText("GPU:");

        jLabel10.setText("Capacidad de la bateria:");

        txtbateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbateriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbateriaKeyTyped(evt);
            }
        });

        jLabel11.setText("CPU:");

        txtcpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcpuKeyReleased(evt);
            }
        });

        jLabel12.setText("principal:");

        jLabel13.setText("frontal:");

        chkflash.setText("flas ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(btnejecutar)
                .addGap(0, 279, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(txtcpu))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtbateria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtgpu)
                            .addComponent(txtgarantia)
                            .addComponent(txtprecio)
                            .addComponent(cmbmarca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtpantalla)
                            .addComponent(txtram))))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtsecundaria, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addComponent(chkflash, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcpu, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                        .addComponent(jLabel12))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkflash))
                .addGap(24, 24, 24)
                .addComponent(btnejecutar)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
       if (Double.parseDouble(txtpantalla.getText())<3.0 || Double.parseDouble(txtpantalla.getText())>6.7){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 3.0 Y 6.7");
          txtpantalla.setText("");
          txtpantalla.requestFocus();
         
        }
        else {txtram.requestFocus();}
               
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void txtpantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyTyped
        
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtpantalla.getText().length()<=2 ||org == '.' && txtpantalla.getText().length()<=2){
            
        evt.consume();
       
            txtpantalla.setText(txtpantalla.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
        
    }//GEN-LAST:event_txtpantallaKeyTyped

    private void txtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtramActionPerformed
           if (Double.parseDouble(txtram.getText())<0.5 || Double.parseDouble(txtram.getText())>6.0){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 0.5 Y 6.0");
          txtram.setText("");
          txtram.requestFocus();
        }
        else {txtgarantia.requestFocus();}
    }//GEN-LAST:event_txtramActionPerformed

    private void txtpantallaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyReleased
        validar();
    }//GEN-LAST:event_txtpantallaKeyReleased

    private void txtpantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyPressed
     
    }//GEN-LAST:event_txtpantallaKeyPressed

    private void txtramKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtramKeyTyped
         char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtram.getText().length()<=2 || org=='.'&& txtram.getText().length()<=2 ){
            
            evt.consume();
            txtram.setText(txtram.getText()+org);
            
       
        }
        
        else{
        evt.consume();
        
        } 
        
        
    }//GEN-LAST:event_txtramKeyTyped

    private void txtgarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgarantiaActionPerformed
         if (Double.parseDouble(txtgarantia.getText())<1.0 || Double.parseDouble(txtgarantia.getText())>24.0){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 1 Y 24");
          txtgarantia.setText("");
          txtgarantia.requestFocus();
        }
        else {txtprecio.requestFocus();}
    }//GEN-LAST:event_txtgarantiaActionPerformed

    private void txtgarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgarantiaKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtgarantia.getText().length()<=2 || org=='.'&& txtgarantia.getText().length()<=2 ){
            
            evt.consume();
            txtgarantia.setText(txtgarantia.getText()+org);
       
        }
        
        else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtgarantiaKeyTyped

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtprecio.getText().length()<=5 || org=='.' && txtprecio.getText().length()<=5){
            
        evt.consume();
       
            txtprecio.setText(txtprecio.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
         if (Double.parseDouble(txtprecio.getText())<0.01 || Double.parseDouble(txtprecio.getText())>999.99){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 999.99 Y 0.01");
          txtprecio.setText("");
          txtprecio.requestFocus();
        }
        else {txtgpu.requestFocus();}
                                        
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprincipalActionPerformed
       
    }//GEN-LAST:event_txtprincipalActionPerformed

    private void txtprincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprincipalKeyTyped
       char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtprincipal.getText().length()<=3 || org=='.'&& txtprincipal.getText().length()<=3 ){
            
        evt.consume();
       
            txtprincipal.setText(txtprincipal.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtprincipalKeyTyped

    private void txtsecundariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecundariaKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtsecundaria.getText().length()<=3 || org=='.' && txtsecundaria.getText().length()<=3 ){
            
        evt.consume();
       
            txtsecundaria.setText(txtsecundaria.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtsecundariaKeyTyped

    private void txtprecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioKeyPressed

    private void btnejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnejecutarActionPerformed
        JOptionPane.showMessageDialog(null, "el puntaje del terminal es: "+ (objeto.refDeMarca(cmbmarca.getSelectedIndex())+objeto.rangoPrecio(Double.parseDouble(txtprecio.getText().toString())+objeto.Ram(Double.parseDouble(txtram.getText().toString())))+objeto.Cpu(Integer.parseInt(txtcpu.getText().toString()))+objeto.bateriapantalla(Integer.parseInt(txtpantalla.getText()), Double.parseDouble(txtbateria.getText().toString()))+(objeto.garantia(Integer.parseInt(txtgarantia.getText().toString())))+objeto.pixelaje(Integer.parseInt(txtsecundaria.getText().toString()), Integer.parseInt(txtprincipal.getText().toString()), chkflash.isSelected())));
       
    }//GEN-LAST:event_btnejecutarActionPerformed

    private void txtgpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgpuKeyTyped
          
        char org = evt.getKeyChar();
        if(Character.isLetter(org)&& txtgpu.getText().length()<=2 ||org == '.' && txtgpu.getText().length()<=2){
            
        evt.consume();
       
            txtgpu.setText(txtgpu.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtgpuKeyTyped

    private void txtbateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbateriaKeyTyped
          
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtbateria.getText().length()<=3 ||org == '.' && txtbateria.getText().length()<=3){
            
        evt.consume();
       
            txtbateria.setText(txtbateria.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtbateriaKeyTyped

    private void txtramKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtramKeyReleased
        validar();
    }//GEN-LAST:event_txtramKeyReleased

    private void txtgarantiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgarantiaKeyReleased
        validar();
    }//GEN-LAST:event_txtgarantiaKeyReleased

    private void txtprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyReleased
       validar();
    }//GEN-LAST:event_txtprecioKeyReleased

    private void txtgpuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgpuKeyReleased
        validar();
    }//GEN-LAST:event_txtgpuKeyReleased

    private void txtbateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbateriaKeyReleased
        validar();
    }//GEN-LAST:event_txtbateriaKeyReleased

    private void txtcpuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpuKeyReleased
        validar();
    }//GEN-LAST:event_txtcpuKeyReleased

    private void txtprincipalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprincipalKeyReleased
        validar();
    }//GEN-LAST:event_txtprincipalKeyReleased

    private void txtsecundariaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecundariaKeyReleased
        validar();
    }//GEN-LAST:event_txtsecundariaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telefonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejecutar;
    private javax.swing.JCheckBox chkflash;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.ButtonGroup propiedades;
    private javax.swing.JTextField txtbateria;
    private javax.swing.JTextField txtcpu;
    private javax.swing.JTextField txtgarantia;
    private javax.swing.JTextField txtgpu;
    private javax.swing.JTextField txtpantalla;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprincipal;
    private javax.swing.JTextField txtram;
    private javax.swing.JTextField txtsecundaria;
    // End of variables declaration//GEN-END:variables

    private void validar() {
        if(txtpantalla.getText().equals("")|| txtram.getText().equals("")|| txtgarantia.getText().equals("")|| txtprecio.getText().equals("")|| txtgpu.getText().equals("")|| txtbateria.getText().equals("")|| txtcpu.getText().equals("")|| txtprincipal.getText().equals("")|| txtsecundaria.getText().equals("")){
           btnejecutar.setEnabled(false);
            
        }else{
            btnejecutar.setEnabled(true);
        
        }
    }
}
