/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia3progra;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author yese
 */
public class telefonos extends javax.swing.JFrame {

    /**
     * Creates new form telefonos
     */
    public telefonos() {
        initComponents();
        txtprincipal.setEnabled(false);
        txtsecundaria.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propiedades = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnucleos = new javax.swing.JTextField();
        txtpantalla = new javax.swing.JTextField();
        txtram = new javax.swing.JTextField();
        txtgarantia = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        cmbmarca = new javax.swing.JComboBox<>();
        rdbcamaraprincipal = new javax.swing.JRadioButton();
        rdbcamarasecundaria = new javax.swing.JRadioButton();
        rdbflash = new javax.swing.JRadioButton();
        txtprincipal = new javax.swing.JTextField();
        txtsecundaria = new javax.swing.JTextField();
        btnejecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PUNTAJE DE MOVILES");

        jLabel2.setText("Cpu numero de nucleos:");

        jLabel3.setText("Tamano de pantalla:");

        jLabel4.setText("Cantidad de RAM:");

        jLabel5.setText("Tiempo de garantia:");

        jLabel6.setText("Precio:");

        jLabel7.setText("Marca ");

        jLabel8.setText("Camara:");

        txtnucleos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnucleosActionPerformed(evt);
            }
        });
        txtnucleos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnucleosKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnucleosKeyTyped(evt);
            }
        });

        txtpantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpantallaActionPerformed(evt);
            }
        });
        txtpantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpantallaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpantallaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpantallaKeyTyped(evt);
            }
        });

        txtram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtramActionPerformed(evt);
            }
        });
        txtram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtramKeyTyped(evt);
            }
        });

        txtgarantia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgarantiaActionPerformed(evt);
            }
        });
        txtgarantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgarantiaKeyTyped(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        txtprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecioKeyTyped(evt);
            }
        });

        cmbmarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NEXUS", "PIXI", "LENOVO", "HUAWEI", "SONY", "APPLE", "SAMSUNG", "ALCATEL", "LG", "OTRA", " " }));

        rdbcamaraprincipal.setText("Principal");
        rdbcamaraprincipal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbcamaraprincipalItemStateChanged(evt);
            }
        });
        rdbcamaraprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcamaraprincipalActionPerformed(evt);
            }
        });

        rdbcamarasecundaria.setText("Secundaria");
        rdbcamarasecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcamarasecundariaActionPerformed(evt);
            }
        });

        propiedades.add(rdbflash);
        rdbflash.setText("Flash");
        rdbflash.setToolTipText("");

        txtprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprincipalActionPerformed(evt);
            }
        });
        txtprincipal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprincipalKeyTyped(evt);
            }
        });

        txtsecundaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsecundariaKeyTyped(evt);
            }
        });

        btnejecutar.setText("Ejecutar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnucleos)
                            .addComponent(txtram)
                            .addComponent(txtgarantia)
                            .addComponent(txtprecio)
                            .addComponent(cmbmarca, 0, 89, Short.MAX_VALUE)
                            .addComponent(txtpantalla)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(btnejecutar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(51, 51, 51)
                                .addComponent(rdbcamaraprincipal)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rdbcamarasecundaria))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtsecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addComponent(rdbflash))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnucleos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtgarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbcamaraprincipal)
                        .addComponent(rdbcamarasecundaria)
                        .addComponent(rdbflash)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtprincipal)
                    .addComponent(txtsecundaria))
                .addGap(18, 18, 18)
                .addComponent(btnejecutar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnucleosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnucleosActionPerformed
        if (Integer.parseInt(txtnucleos.getText())<1 || Integer.parseInt(txtnucleos.getText())>12){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 1 Y 12");
          txtnucleos.setText("");
          txtnucleos.requestFocus();
        }
        else {txtpantalla.requestFocus();}
    }//GEN-LAST:event_txtnucleosActionPerformed

    private void txtnucleosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnucleosKeyTyped
       int caracteres=2;
       char letra= evt.getKeyChar();
       if (Character.isLetter(letra)){
           evt.consume();
           JOptionPane.showMessageDialog(null,"INGRESE SOLO NUMEROS");
           
       }
       if (txtnucleos.getText().length()>=caracteres){
           evt.consume();
       }
       
    }//GEN-LAST:event_txtnucleosKeyTyped

    private void txtpantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpantallaActionPerformed
       if (Double.parseDouble(txtpantalla.getText())<3.0 || Double.parseDouble(txtpantalla.getText())>6.7){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 3.0 Y 6.7");
          txtpantalla.setText("");
          txtpantalla.requestFocus();
        }
        else {txtram.requestFocus();}
               
    }//GEN-LAST:event_txtpantallaActionPerformed

    private void txtnucleosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnucleosKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txtpantalla.requestFocus();
        }
    }//GEN-LAST:event_txtnucleosKeyPressed

    private void txtpantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyTyped
        
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtpantalla.getText().length()<=2 ){
            
        evt.consume();
        if (txtpantalla.getText().length()==2){
            txtpantalla.setText(txtpantalla.getText()+org);
        }else {
            txtpantalla.setText(txtpantalla.getText()+org+".");
        }
        
        }else{
        evt.consume();
        
        }
        
    }//GEN-LAST:event_txtpantallaKeyTyped

    private void txtramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtramActionPerformed
           if (Double.parseDouble(txtram.getText())<0.5 || Double.parseDouble(txtram.getText())>6.0){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 0.5 Y 6.0");
          txtram.setText("");
          txtram.requestFocus();
        }
        else {txtgarantia.requestFocus();}
    }//GEN-LAST:event_txtramActionPerformed

    private void txtpantallaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpantallaKeyReleased

    private void txtpantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpantallaKeyPressed
     
    }//GEN-LAST:event_txtpantallaKeyPressed

    private void txtramKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtramKeyTyped
         char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtram.getText().length()<=2 ){
            
        evt.consume();
        if (txtram.getText().length()==2){
            txtram.setText(txtram.getText()+org);
        }else {
            txtram.setText(txtram.getText()+org+".");
        }
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtramKeyTyped

    private void txtgarantiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgarantiaActionPerformed
         if (Double.parseDouble(txtgarantia.getText())<1.0 || Double.parseDouble(txtgarantia.getText())>24.0){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 1 Y 24");
          txtgarantia.setText("");
          txtgarantia.requestFocus();
        }
        else {txtprecio.requestFocus();}
    }//GEN-LAST:event_txtgarantiaActionPerformed

    private void txtgarantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgarantiaKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtgarantia.getText().length()<=2 || org=='.'&& txtgarantia.getText().length()<=2 ){
            
        
            txtgarantia.setText(txtgarantia.getText()+org);
       
        }
        
        else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtgarantiaKeyTyped

    private void txtprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtprecio.getText().length()<=5 || org=='.' && txtprecio.getText().length()<=5){
            
        evt.consume();
       
            txtprecio.setText(txtprecio.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtprecioKeyTyped

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
         if (Double.parseDouble(txtprecio.getText())<0.01 || Double.parseDouble(txtprecio.getText())>999.99){
            JOptionPane.showMessageDialog(null,"INGRESE UN NUMERO ENTRE 999.99 Y 0.01");
          txtprecio.setText("");
          txtprecio.requestFocus();
        }
        else {rdbcamaraprincipal.requestFocus();}
                                        
    }//GEN-LAST:event_txtprecioActionPerformed

    private void rdbcamaraprincipalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbcamaraprincipalItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbcamaraprincipalItemStateChanged

    private void rdbcamaraprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcamaraprincipalActionPerformed
         
        if (rdbcamaraprincipal.isSelected()){
        txtprincipal.setEnabled(true);
        
        }else{
        txtprincipal.setEnabled(false);
        }
    }//GEN-LAST:event_rdbcamaraprincipalActionPerformed

    private void rdbcamarasecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcamarasecundariaActionPerformed
           if (rdbcamarasecundaria.isSelected()){
        txtsecundaria.setEnabled(true);
       
        }else{
           txtsecundaria.setEnabled(false);
           }
    }//GEN-LAST:event_rdbcamarasecundariaActionPerformed

    private void txtprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprincipalActionPerformed
       
    }//GEN-LAST:event_txtprincipalActionPerformed

    private void txtprincipalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprincipalKeyTyped
       char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtprincipal.getText().length()<=3 || org=='.'&& txtprincipal.getText().length()<=3 ){
            
        evt.consume();
       
            txtprincipal.setText(txtprincipal.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtprincipalKeyTyped

    private void txtsecundariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecundariaKeyTyped
        char org = evt.getKeyChar();
        if(Character.isDigit(org)&& txtsecundaria.getText().length()<=3 || org=='.' && txtsecundaria.getText().length()<=3 ){
            
        evt.consume();
       
            txtsecundaria.setText(txtsecundaria.getText()+org);
       
        
        }else{
        evt.consume();
        
        }
    }//GEN-LAST:event_txtsecundariaKeyTyped

    private void txtprecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telefonos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telefonos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnejecutar;
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.ButtonGroup propiedades;
    private javax.swing.JRadioButton rdbcamaraprincipal;
    private javax.swing.JRadioButton rdbcamarasecundaria;
    private javax.swing.JRadioButton rdbflash;
    private javax.swing.JTextField txtgarantia;
    private javax.swing.JTextField txtnucleos;
    private javax.swing.JTextField txtpantalla;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtprincipal;
    private javax.swing.JTextField txtram;
    private javax.swing.JTextField txtsecundaria;
    // End of variables declaration//GEN-END:variables
}
